#pragma once

#define VIAL_KEYBOARD_UID {0x0E, 0xBB, 0x9B, 0x62, 0xD6, 0x78, 0xFD, 0xBE}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 12 }

#define VIAL_COMBO_ENTRIES 69
#define DYNAMIC_KEYMAP_LAYER_COUNT 5
#define TAPPING_TERM 250

